<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vfb-14</name>
   <tag></tag>
   <elementGuidId>76955ed2-91a9-44e6-bcb9-2ae91125be68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92ca793d-4a4f-4329-a54d-57c1a6d86bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>aff21602-63a7-4cfb-8313-ffbe34cc6f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-14</value>
      <webElementGuid>afe98e0b-b1fe-4def-934d-30e243dd3361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-14</value>
      <webElementGuid>86c911ad-331e-45d1-ba98-12e4620b58e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium  required  email </value>
      <webElementGuid>e25974ac-e15e-4c52-81da-50e043bf852e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-14&quot;)</value>
      <webElementGuid>0839aeba-59c7-479d-b5e5-87a73b2bcd9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-14']</value>
      <webElementGuid>7df0a575-2d18-4b62-b306-58a86a5b2c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-14']/input</value>
      <webElementGuid>4e07ed50-bc36-494b-b4a7-e011afcd5417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/input</value>
      <webElementGuid>62e1f378-8088-4d2b-8397-d7d9f9f193e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'vfb-14' and @id = 'vfb-14']</value>
      <webElementGuid>4d227943-b147-4b4b-a075-57dc20df6c4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
