<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Functional Testing_vfb-20</name>
   <tag></tag>
   <elementGuidId>e6327009-0c12-41bd-9ef1-cc22a3812d93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-20-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-20-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71022ebe-3235-40f2-a488-e6068a57a269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c7bc5dff-f7b2-4ab2-8f46-b25ef9190706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-20[]</value>
      <webElementGuid>c1577a69-a055-457a-ab7b-ca937795d6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-20-5</value>
      <webElementGuid>b5f32cb1-5beb-49ca-9bd1-c8981b75e71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Others</value>
      <webElementGuid>796b6b20-4a5d-4e51-9ef1-7e7ea72f7bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-checkbox  </value>
      <webElementGuid>538a2aeb-d55b-4641-8fdf-2b1dcba8fbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-20-5&quot;)</value>
      <webElementGuid>d9b2ed08-f76b-460e-95ff-e4d72f954bdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-20-5']</value>
      <webElementGuid>9b889ddf-2593-40a8-a073-b961c4aa101f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-20']/div/span[6]/input</value>
      <webElementGuid>07e278f1-05f7-4c83-87f0-bf71b2665213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/input</value>
      <webElementGuid>69d9edf9-9cc6-41f8-aa07-97b82eb451db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'vfb-20[]' and @id = 'vfb-20-5']</value>
      <webElementGuid>5b55cd71-c98e-499b-b398-df03309982f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
