<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Enter in MMDDYY Format</name>
   <tag></tag>
   <elementGuidId>a2e41308-135c-46b5-bb35-8e05c5f09aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item-vfb-18']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item-vfb-18 > span.vfb-span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ecf80da-bef9-46f0-84f8-52ed065d07c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-span</value>
      <webElementGuid>11351406-c795-41d3-961d-9ba260b543d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter in MM/DD/YY Format</value>
      <webElementGuid>8164fcf1-8e76-4356-95c6-a9e0894a2682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-vfb-18&quot;)/span[@class=&quot;vfb-span&quot;]</value>
      <webElementGuid>ccb3f295-7a01-496d-9390-aa5baa717aef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-18']/span</value>
      <webElementGuid>62ecb7d3-5161-4d45-8f03-063a449c4683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Demo'])[1]/following::span[1]</value>
      <webElementGuid>9f7b195a-4cd9-412b-91fa-1e5171833f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[1]</value>
      <webElementGuid>2f6535d8-1c6b-4f88-a06a-075f1c3764a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convenient Time'])[1]/preceding::span[1]</value>
      <webElementGuid>91901585-7d48-46de-bd84-85d1aa060b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/ul/li[6]/span</value>
      <webElementGuid>174ba654-1916-47e6-824a-8ed17b2f4e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Enter in MM/DD/YY Format' or . = 'Enter in MM/DD/YY Format')]</value>
      <webElementGuid>ea54d8eb-cc5e-4411-8a88-1ed7f18fc326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
